export const products = [
  {
    id: 1,
    name: 'Ultra Laptop 14"',
    brand: 'Nova',
    price: 1200,
    sale: 20,
    image: './src/imgs/products/laptop.jpg',
    sliderImage:
      'https://images.unsplash.com/photo-1755127761410-0c00c398c308?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    category: 'Computers',
    rating: 4.6,
    desc: 'Ultrabook with long battery',
    thumbnails: [
      './src/imgs/products/laptop.jpg',
      './src/imgs/products/phone.jpg',
      './src/imgs/products/laptop.jpg',
      './src/imgs/products/phone.jpg',
      './src/imgs/products/laptop.jpg',
    ],
    reviews: [
      {
        name: 'Michael Johnson',
        date: 'August 15, 2025',
        rating: 4.5,
        review:
          'This laptop exceeded my expectations. The display is absolutely stunning, and the battery life is as advertised. I can easily get through a full workday without charging.',
      },
      {
        name: 'Sophia Lee',
        date: 'August 20, 2025',
        rating: 4.7,
        review: 'Lightweight and powerful. Perfect for travel and remote work. Runs smoothly with multiple apps open.',
      },
    ],
    tags: ['ssd', 'light', 'work'],
    newArrival: false,

    metaItems: {
      Weight: '2.8 lbs (1.27 kg)',
      SKU: 'NOVA-LTP-14U-2025',
      Dimensions: '12.7" x 8.9" x 0.6"',
      Manufacturer: 'Nova Technologies',
      Warranty: '2 Years Limited',
      Model: 'UltraBook 14 Pro',
      Release: '2025',
    },

    specItems: {
      Display: '14" IPS, 2560x1600, 400 nits',
      Processor: 'Intel Core i7-1260P',
      Memory: '16GB LPDDR5',
      Storage: '512GB NVMe SSD',
      Graphics: 'Intel Iris Xe',
      Battery: 'Up to 12 hours',
      Ports: '2x Thunderbolt 4, 1x USB-A, HDMI, 3.5mm audio',
      Wireless: 'Wi-Fi 6E, Bluetooth 5.2',
      'Operating System': 'Windows 11 Pro',
      Color: 'Space Gray',
    },
  },

  {
    id: 2,
    name: 'Smartphone X',
    brand: 'Zenix',
    price: 799,
    sale: 20,
    image: './src/imgs/products/phone.jpg',
    category: 'Phones',
    rating: 4.3,
    desc: 'Flagship display & camera',
    thumbnails: [],
    reviews: [
      {
        name: 'Daniel Kim',
        date: 'August 10, 2025',
        rating: 4.2,
        review:
          'The camera is incredible, especially in low light. The screen is bright and smooth. Battery could be better, but fast charging makes up for it.',
      },
      {
        name: 'Emily Carter',
        date: 'August 18, 2025',
        rating: 4.4,
        review: 'Love the design and performance. Handles games easily and 5G speed is excellent.',
      },
    ],
    tags: ['android', '5g'],
    newArrival: false,

    metaItems: {
      Weight: '6.4 oz (182 g)',
      SKU: 'ZENIX-SPX-2025',
      Dimensions: '6.3" x 2.9" x 0.3"',
      Warranty: '1 Year',
      Model: 'X-Pro 5G',
      Release: '2025',
    },

    specItems: {
      Display: '6.7" AMOLED, 3200x1440, 120Hz',
      Processor: 'Snapdragon 8 Gen 3',
      Memory: '12GB RAM',
      Storage: '256GB UFS 4.0',
      Camera: '108MP + 12MP + 8MP, 32MP Front',
      Battery: '4800mAh, 65W Fast Charge',
      Wireless: '5G, Wi-Fi 7, Bluetooth 5.3',
      OS: 'Android 14',
      Color: 'Midnight Black',
    },
  },

  {
    id: 3,
    name: 'Wireless Headphones',
    brand: 'Auro',
    price: 149,
    sale: 20,
    image: './src/imgs/products/headphones.jpg',
    sliderImage: './src/imgs/products/headphones.jpg',
    category: 'Audio',
    rating: 4.7,
    desc: 'ANC, comfy pads',
    thumbnails: [],
    reviews: [
      {
        name: 'Olivia Martinez',
        date: 'July 28, 2025',
        rating: 4.8,
        review: 'Noise cancellation works amazingly well on flights. Super comfortable for long listening sessions.',
      },
      {
        name: 'James Anderson',
        date: 'August 12, 2025',
        rating: 4.6,
        review: 'Great sound quality with deep bass. Build feels premium. Would love slightly longer battery life.',
      },
    ],
    tags: ['bluetooth', 'anc'],
    newArrival: false,

    metaItems: {
      Weight: '9.6 oz (272 g)',
      SKU: 'AURO-WH-ANC-2025',
      Dimensions: '7.9" x 6.7" x 3.2"',
      Warranty: '1 Year',
      Model: 'Auro ANC Pro',
    },

    specItems: {
      Driver: '40mm Neodymium',
      Battery: 'Up to 40 hours',
      Charging: 'USB-C Fast Charge (10min = 5hrs)',
      Wireless: 'Bluetooth 5.2',
      ANC: 'Hybrid Active Noise Cancellation',
      Microphones: 'Dual Beamforming',
      Color: 'Matte Black',
    },
  },

  {
    id: 4,
    name: '27" 4K Monitor',
    brand: 'Vision',
    price: 399,
    sale: 20,
    image: './src/imgs/products/monitor.jpg',
    category: 'Monitors',
    rating: 4.4,
    desc: 'Crisp 4K IPS',
    thumbnails: [],
    reviews: [
      {
        name: 'Brian Walker',
        date: 'August 1, 2025',
        rating: 4.5,
        review: 'Colors are accurate, brightness is solid, and 144Hz is smooth for gaming. Worth the price.',
      },
      {
        name: 'Hannah Green',
        date: 'August 14, 2025',
        rating: 4.3,
        review: 'Excellent for design work. The HDR is decent, though not the brightest.',
      },
    ],
    tags: ['gaming', 'design'],

    metaItems: {
      Weight: '14.3 lbs (6.5 kg)',
      SKU: 'VISION-MNTR-27UHD',
      Dimensions: '24.2" x 14.3" x 2.1"',
      Warranty: '3 Years',
      Model: 'Vision 27 Pro',
    },

    specItems: {
      Display: '27" IPS, 3840x2160, 144Hz',
      Brightness: '350 nits',
      Ports: '2x HDMI 2.1, 1x DisplayPort 1.4, USB-C',
      Response: '1ms GTG',
      Color: 'Black',
      Features: 'HDR10, sRGB 100%',
    },
  },

  {
    id: 5,
    name: 'Mechanical Keyboard',
    brand: 'KeyPro',
    price: 99,
    sale: 20,
    image: './src/imgs/products/keyboard.jpg',
    sliderImage: './src/imgs/products/keyboard.jpg',
    category: 'Accessories',
    rating: 4.2,
    desc: 'Hot-swap switches',
    thumbnails: [],
    reviews: [
      {
        name: 'Lucas White',
        date: 'August 6, 2025',
        rating: 4.3,
        review: 'Keys feel great and the RGB looks amazing. Hot-swap is a big plus.',
      },
      {
        name: 'Isabella Brown',
        date: 'August 19, 2025',
        rating: 4.1,
        review: 'Solid build quality. A bit loud for the office but perfect for gaming.',
      },
    ],
    tags: ['rgb', 'typing'],

    metaItems: {
      Weight: '2.1 lbs (0.95 kg)',
      SKU: 'KEYPRO-MK-2025',
      Dimensions: '17.3" x 5.5" x 1.6"',
      Warranty: '1 Year',
      Model: 'KeyPro TKL RGB',
    },

    specItems: {
      Switches: 'Hot-swappable, MX-compatible',
      Lighting: 'Per-key RGB',
      Connectivity: 'USB-C Detachable Cable',
      Layout: 'Tenkeyless (87 keys)',
      Build: 'Aluminum top plate',
      Color: 'Black',
    },
  },

  {
    id: 6,
    name: 'Gaming Mouse',
    brand: 'Swift',
    price: 59,
    sale: 20,
    image: './src/imgs/products/mouse.jpg',
    category: 'Accessories',
    rating: 4.1,
    desc: 'Lightweight 67g',
    thumbnails: [],
    reviews: [
      {
        name: 'Nathan Scott',
        date: 'July 30, 2025',
        rating: 4.0,
        review: 'Super light and accurate sensor. Battery life is okay, not the longest.',
      },
    ],
    tags: ['gaming', 'dpi'],
    newArrival: false,

    metaItems: {
      Weight: '2.4 oz (67 g)',
      SKU: 'SWIFT-GM-2025',
      Dimensions: '4.7" x 2.6" x 1.5"',
      Warranty: '1 Year',
      Model: 'Swift Pro 67',
    },

    specItems: {
      Sensor: 'PixArt 3395',
      DPI: '100 – 26,000 DPI',
      Buttons: '6 Programmable',
      Connectivity: 'USB-C / Wireless 2.4GHz',
      Battery: '70 hrs (wireless)',
      Color: 'Matte Black',
    },
  },

  {
    id: 7,
    name: 'Action Camera 4K',
    brand: 'CamGo',
    price: 249,
    sale: 20,
    image: './src/imgs/products/camera.jpg',
    sliderImage: './src/imgs/products/camera.jpg',
    category: 'Cameras',
    rating: 4.0,
    desc: 'Waterproof 30m',
    thumbnails: [],
    reviews: [
      {
        name: 'David Lopez',
        date: 'August 2, 2025',
        rating: 4.1,
        review: 'Used it while snorkeling, footage is clear and stable. Battery could last longer.',
      },
    ],
    tags: ['sport', 'travel'],

    metaItems: {
      Weight: '4.1 oz (116 g)',
      SKU: 'CAMGO-4K-2025',
      Dimensions: '2.6" x 1.7" x 1.2"',
      Warranty: '1 Year',
      Model: 'CamGo HeroX',
    },

    specItems: {
      Sensor: '1/2" CMOS 20MP',
      Video: '4K60, 2.7K120, 1080p240',
      Waterproof: 'Up to 30m',
      Battery: '1350mAh (2 hrs)',
      Connectivity: 'Wi-Fi, Bluetooth',
      Storage: 'microSD up to 512GB',
      Color: 'Black',
    },
  },

  {
    id: 8,
    name: 'Smartwatch S',
    brand: 'Pulse',
    price: 199,
    sale: 20,
    image: './src/imgs/products/watch.jpg',
    category: 'Wearables',
    rating: 4.3,
    desc: 'GPS, HRM, NFC',
    thumbnails: [],
    reviews: [
      {
        name: 'Grace Hall',
        date: 'August 5, 2025',
        rating: 4.2,
        review: 'Tracks fitness accurately and notifications are reliable. Battery lasts about 5 days for me.',
      },
    ],
    tags: ['fitness', 'nfc'],

    metaItems: {
      Weight: '1.6 oz (45 g)',
      SKU: 'PULSE-SMRT-S',
      Dimensions: '1.7" case, 11mm thickness',
      Warranty: '1 Year',
      Model: 'Smartwatch S Gen3',
    },

    specItems: {
      Display: '1.7" AMOLED, Always-On',
      Sensors: 'HRM, SpO2, GPS, Compass',
      Battery: 'Up to 7 days',
      Charging: 'Magnetic fast charging',
      WaterResistant: '5ATM',
      Wireless: 'Bluetooth 5.2, NFC',
      OS: 'PulseOS',
      Color: 'Silver',
    },
  },

  {
    id: 9,
    name: 'Bluetooth Speaker',
    brand: 'Boom',
    price: 89,
    sale: 20,
    image: './src/imgs/products/speaker.jpg',
    sliderImage: './src/imgs/products/speaker.jpg',
    category: 'Audio',
    rating: 4.5,
    desc: 'Big sound in small size',
    thumbnails: [],
    reviews: [
      {
        name: 'Ethan Miller',
        date: 'August 11, 2025',
        rating: 4.5,
        review: 'Loud for its size and the bass is surprisingly strong. Great for outdoor use.',
      },
    ],
    tags: ['portable'],

    metaItems: {
      Weight: '1.2 lbs (540 g)',
      SKU: 'BOOM-BTSPKR-2025',
      Dimensions: '7.5" x 3.2" x 3.2"',
      Warranty: '1 Year',
      Model: 'Boom Mini X',
    },

    specItems: {
      Output: '20W RMS',
      Battery: '12 hrs playback',
      Charging: 'USB-C',
      Wireless: 'Bluetooth 5.3',
      WaterResistant: 'IPX7',
      Color: 'Blue',
    },
  },

  {
    id: 10,
    name: 'Smart Bulb (2-pack)',
    brand: 'Lumo',
    price: 39,
    sale: 20,
    image: './src/imgs/products/bulb.jpg',
    category: 'Smart Home',
    rating: 4.1,
    desc: 'RGB, voice control',
    thumbnails: [],
    reviews: [
      {
        name: 'Mia Wilson',
        date: 'August 9, 2025',
        rating: 4.0,
        review: 'Easy to set up and works great with Alexa. Brightness is good for a room.',
      },
    ],
    tags: ['home', 'iot'],

    metaItems: {
      Weight: '4.2 oz (120 g) each',
      SKU: 'LUMO-SMBULB-2P',
      Dimensions: '2.4" x 4.3"',
      Warranty: '1 Year',
      Model: 'Lumo Smart RGB',
    },

    specItems: {
      Brightness: '800 lumens',
      Color: '16M RGB + Warm/Cool White',
      Wireless: 'Wi-Fi 2.4GHz',
      Control: 'Voice (Alexa/Google), App',
      Power: '9W LED',
      Lifespan: '25,000 hrs',
    },
  },

  {
    id: 11,
    name: 'Tablet 11"',
    brand: 'Nova',
    price: 349,
    sale: 20,
    image: './src/imgs/products/tablet.jpg',
    sliderImage: './src/imgs/products/tablet.jpg',
    category: 'Computers',
    rating: 4.2,
    desc: 'Great for media',
    thumbnails: [],
    reviews: [
      {
        name: 'Chloe Adams',
        date: 'August 7, 2025',
        rating: 4.2,
        review: 'Perfect for media and browsing. Screen is sharp. Could use more storage by default.',
      },
    ],
    tags: ['study', 'kids'],

    metaItems: {
      Weight: '1.1 lbs (500 g)',
      SKU: 'NOVA-TBLT-11-2025',
      Dimensions: '9.8" x 6.5" x 0.3"',
      Warranty: '1 Year',
      Model: 'NovaTab 11',
    },

    specItems: {
      Display: '11" IPS, 2000x1200',
      Processor: 'MediaTek Dimensity 9000',
      Memory: '8GB RAM',
      Storage: '128GB',
      Battery: '7500mAh (10 hrs)',
      Wireless: 'Wi-Fi 6, Bluetooth 5.2',
      OS: 'Android 14',
      Color: 'Silver',
    },
  },

  {
    id: 12,
    name: 'Noise Cancelling Earbuds',
    brand: 'Auro',
    price: 129,
    sale: 20,
    image: './src/imgs/products/earbuds.jpg',
    category: 'Audio',
    rating: 4.4,
    desc: 'Compact & clear',
    thumbnails: [],
    reviews: [
      {
        name: 'Daniel Cooper',
        date: 'August 14, 2025',
        rating: 4.5,
        review:
          'These earbuds have excellent noise cancelling for their size. They fit securely, and the sound quality is rich with deep bass.',
      },
      {
        name: 'Sophia Martinez',
        date: 'August 16, 2025',
        rating: 4.0,
        review:
          'The sound is impressive, especially for podcasts and classical music. Battery life could be slightly better though.',
      },
      {
        name: 'Ethan Williams',
        date: 'August 19, 2025',
        rating: 4.6,
        review:
          'Perfect for commuting! The ANC blocks out subway noise very well, and they are super comfortable for long use.',
      },
    ],
    tags: ['anc', 'travel'],
    metaItems: {
      Weight: '0.3 oz (8.5 g each)',
      SKU: 'AURO-EB-NC-2025',
      Dimensions: '0.9" x 0.8" x 1.0" (per earbud)',
      Battery: '6 hours (earbuds) + 18 hours (case)',
      Waterproof: 'IPX4 (splash resistant)',
    },
    specItems: {
      Driver: '10mm Dynamic Drivers',
      NoiseCancelling: 'Active Noise Cancelling (ANC)',
      Microphones: 'Dual beamforming mics',
      Connectivity: 'Bluetooth 5.3',
      Charging: 'USB-C, Wireless Charging (Qi)',
      BatteryLife: 'Up to 24 hours with case',
      Controls: 'Touch controls + Voice assistant support',
      Wireless: 'AAC, SBC codec support',
      Color: 'Matte Black',
      Compatibility: 'iOS, Android, Windows',
    },
  },
  {
    id: 13,
    name: 'Ultra Laptop 14"',
    brand: 'Nova',
    price: 1200,
    sale: 20,
    image: './src/imgs/products/laptop.jpg',
    sliderImage: './src/imgs/products/laptop.jpg',
    category: 'Computers',
    rating: 4.6,
    desc: 'Ultrabook with long battery',
    thumbnails: [
      './src/imgs/products/laptop.jpg',
      './src/imgs/products/phone.jpg',
      './src/imgs/products/laptop.jpg',
      './src/imgs/products/phone.jpg',
      './src/imgs/products/laptop.jpg',
    ],
    reviews: [
      {
        name: 'Michael Johnson',
        date: 'August 15, 2025',
        rating: 4.5,
        review:
          'This laptop exceeded my expectations. The display is absolutely stunning, and the battery life is as advertised. I can easily get through a full workday without charging.',
      },
      {
        name: 'Sophia Lee',
        date: 'August 20, 2025',
        rating: 4.7,
        review: 'Lightweight and powerful. Perfect for travel and remote work. Runs smoothly with multiple apps open.',
      },
    ],
    tags: ['ssd', 'light', 'work'],
    newArrival: false,

    metaItems: {
      Weight: '2.8 lbs (1.27 kg)',
      SKU: 'NOVA-LTP-14U-2025',
      Dimensions: '12.7" x 8.9" x 0.6"',
      Manufacturer: 'Nova Technologies',
      Warranty: '2 Years Limited',
      Model: 'UltraBook 14 Pro',
      Release: '2025',
    },
  },
];
