export const products = [
  {
    id: 1,
    name: 'Ultra Laptop 14"',
    brand: 'Nova',
    price: 1200,
    image: './src/imgs/products/laptop.jpg',
    category: 'Computers',
    stock: 8,
    rating: 4.6,
    desc: 'Ultrabook with long battery',
    tags: ['ssd', 'light', 'work'],
  },
  {
    id: 2,
    name: 'Smartphone X',
    brand: 'Zenix',
    price: 799,
    image: './src/imgs/products/phone.jpg',
    category: 'Phones',
    stock: 15,
    rating: 4.3,
    desc: 'Flagship display & camera',
    tags: ['android', '5g'],
  },
  {
    id: 3,
    name: 'Wireless Headphones',
    brand: 'Auro',
    price: 149,
    image: './src/imgs/products/headphones.jpg',
    category: 'Audio',
    stock: 25,
    rating: 4.7,
    desc: 'ANC, comfy pads',
    tags: ['bluetooth', 'anc'],
  },
  {
    id: 4,
    name: '27" 4K Monitor',
    brand: 'Vision',
    price: 399,
    image: './src/imgs/products/monitor.jpg',
    category: 'Monitors',
    stock: 10,
    rating: 4.4,
    desc: 'Crisp 4K IPS',
    tags: ['gaming', 'design'],
  },
  {
    id: 5,
    name: 'Mechanical Keyboard',
    brand: 'KeyPro',
    price: 99,
    image: './src/imgs/products/keyboard.jpg',
    category: 'Accessories',
    stock: 30,
    rating: 4.2,
    desc: 'Hot-swap switches',
    tags: ['rgb', 'typing'],
  },
  {
    id: 6,
    name: 'Gaming Mouse',
    brand: 'Swift',
    price: 59,
    image: './src/imgs/products/mouse.jpg',
    category: 'Accessories',
    stock: 40,
    rating: 4.1,
    desc: 'Lightweight 67g',
    tags: ['gaming', 'dpi'],
  },
  {
    id: 7,
    name: 'Action Camera 4K',
    brand: 'CamGo',
    price: 249,
    image: './src/imgs/products/camera.jpg',
    category: 'Cameras',
    stock: 12,
    rating: 4.0,
    desc: 'Waterproof 30m',
    tags: ['sport', 'travel'],
  },
  {
    id: 8,
    name: 'Smartwatch S',
    brand: 'Pulse',
    price: 199,
    image: './src/imgs/products/watch.jpg',
    category: 'Wearables',
    stock: 20,
    rating: 4.3,
    desc: 'GPS, HRM, NFC',
    tags: ['fitness', 'nfc'],
  },
  {
    id: 9,
    name: 'Bluetooth Speaker',
    brand: 'Boom',
    price: 89,
    image: './src/imgs/products/speaker.jpg',
    category: 'Audio',
    stock: 22,
    rating: 4.5,
    desc: 'Big sound in small size',
    tags: ['portable'],
  },
  {
    id: 10,
    name: 'Smart Bulb (2-pack)',
    brand: 'Lumo',
    price: 39,
    image: './src/imgs/products/bulb.jpg',
    category: 'Smart Home',
    stock: 50,
    rating: 4.1,
    desc: 'RGB, voice control',
    tags: ['home', 'iot'],
  },
  {
    id: 11,
    name: 'Tablet 11"',
    brand: 'Nova',
    price: 349,
    image: './src/imgs/products/tablet.jpg',
    category: 'Computers',
    stock: 14,
    rating: 4.2,
    desc: 'Great for media',
    tags: ['study', 'kids'],
  },
  {
    id: 12,
    name: 'Noise Cancelling Earbuds',
    brand: 'Auro',
    price: 129,
    image: './src/imgs/products/earbuds.jpg',
    category: 'Audio',
    stock: 35,
    rating: 4.4,
    desc: 'Compact & clear',
    tags: ['anc', 'travel'],
  },
];
